export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_Fail = "FETCH_CATEGORY_Fail";

export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_Fail = "FETCH_PRODUCT_Fail";

// product

export const FETCH_FLASH_PRODUCT_START = "FETCH_FLAST_PRODUCT_START";
export const FETCH_FLASH_PRODUCT_SUCCESS = "FETCH_FLAST_PRODUCT_SUCCESS";
export const FETCH_FLASH_PRODUCT_Fail = "FETCH_FLAST_PRODUCT_Fail";
